### ISSUE TITLE
[ Quest ] - Uso de @Column e @Table em Entitys

### ISSUE THREAD

**Issue by raunerlucas** [raunerlucas/soa#10]
## Detalhes
* Se o nome do atributo já é "cnpj", porque está identificando a coluna com o mesmo nome?
   * E porque dizer que pode ser nullable?
* Se o nome da classe já é fornecedor por quer está afirmando isso novamente?

**Comment by Bruhollanda** [comment]
"Nullable = false" = não pode ser nulo

 @Table e @column especificam os nomes da tabela e das colunas no banco de dados.
 No application.properties consta que a nomenclatura do hibernate é física
 
 `spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
`
 
 fazendo com que os nomes das tabelas e colunas sejam explícitos e não exatamente iguais as variaveis da entidade.
