### ISSUE TITLE
[ Arquivo ] - Nome das pastas centrais

### ISSUE THREAD

**Issue by raunerlucas** [raunerlucas/soa#2]
### Detalhes  
O nome da pasta dentro da main/java define de maneira direta o nome do domínio, mas a leitura será dada o contrario.
Desse modo, o que está atualmente como `main/java/br/edu/ifto/soa_rest` será convertido para a seguinte URL soa_rest.ifto.edu.br

### Esperado 
Este deve ser uma replica em outra tecnologia, do projeto [Trabalho_SOA](https://github.com/raunerlucas/soa/tree/main/Trabalho_SAO).
Por conta disso deve seguir o mesmo padrão de diretórios: `com/loja_moveis`.

## Implementação
De  `main/java/br/edu/ifto/soa_rest`  para  `main/java/com/loja_moveis`

**Comment by Bruhollanda** [comment]
done
