### ISSUE TITLE
[ Feat ] - Fornecedor Controller

### ISSUE THREAD

**Issue by raunerlucas** [raunerlucas/soa#4]
## Detalhes
Usando os padrões de implementação Restful.
EndPoints esperados
* Cadastro de Fornecedor
* Atualizar Fornecedor
* Desativa (Remolver) Fornecedor (Fornecedor deve ter um atributo "Ativo" partir desse será false)
* Lista os Fornecedores cadastrados (Esse deve ser o padrão de resposta para esse controller)
* Listar paginado os Fornecedores cadastrados 
* Listar um Fornecedores especifico cadastrados

**Comment by Bruhollanda** [comment]
done
